// src/components/CustomSelect.vue
<template>
  <div
    class="custom-select"
    @blur="isOpen = false"
  >
    <div
      class="custom-select__wrapper"
      :class="{'custom-select__wrapper--opened': isOpen}"
    >
      <div
        class="custom-select__input"
        @click="isOpen = !isOpen"
      >
        <div class="custom-select__input-text">
          {{ selected.length !== 0 ? selected.join(', ') : $t('placeholder') }}
        </div>
        <svg
          v-svg
          symbol="arrow-left"
          class="arrow"
          :class="{
            'arrow--top': isOpen,
            'arrow--bottom': !isOpen
          }"
        />
      </div>
      <div
        v-if="isOpen"
        class="custom-select__items"
      >
        <div
          v-for="(option, index) of options"
          :key="index"
          class="custom-select__item"
          @click="onItemClick(option)"
        >
          <svg
            v-if="selected.includes(option)"
            v-svg
            symbol="checkbox-checked"
            class="custom-select__item-checkbox"
          />
          <svg
            v-else
            v-svg
            symbol="checkbox"
            class="custom-select__item-checkbox"
          />
          <div class="custom-select__item-text">
            {{ option }}
          </div>
        </div>
        <div
          class="custom-select__item"
          @click="selected = []"
        >
          <span class="custom-select__remove-button">
            <svg
              v-svg
              symbol="cross"
            />
            {{ $t('reset') }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<i18n>
{
  "en": {
    "reset": "Reset",
    "placeholder": "All categories"
  },
  "ru": {
    "reset": "Сброс",
    "placeholder": "Все категории"
  }
}
</i18n>

<script lang="ts">
import { Vue, Component, Prop } from 'vue-property-decorator';
// eslint-disable-next-line no-unused-vars
import { PropType } from 'vue';

@Component
/**
 * Custom select with multiple choice
 */
export default class CustomSelect extends Vue {
  /**
   * Array of selected values
   */
  private selected: string[] = [];

  @Prop({
    type: Array as PropType<string[]>,
    required: true
  })
  /**
   * Array of available options
   */
  private options!: string[];

  /**
   * Is custom select open
   * @private
   */
  private isOpen: boolean = false;

  /**
   * Handler for click on item in dropdown
   * @param value - value of clicked item
   * @private
   */
  private onItemClick(value: string): void {
    if (this.selected.includes(value)) {
      const index = this.selected.indexOf(value);

      this.selected.splice(index, 1);
    } else {
      this.selected.push(value);
    }
  }
}
</script>

<style>
@import "../styles/variables.css";
@import "../styles/custom-properties.css";

.custom-select {
  @apply(--font-sans-serif-light);

  position: relative;
  z-index: 1;

  flex: 1;

  /** It needs for displaying dropdown over content */
  height: 38.4px;
  margin-right: 16px;

  color: var(--color-gray-main);
  font-size: 14px;

  user-select: none;

  &__wrapper {
    position: absolute;

    width: 100%;

    background: var(--color-white);
    border: .5px solid #F2F2F2;
    border-radius: 2px;

    &--opened {
      @apply(--box-shadow-medium);
    }
  }

  &__input {
    display: flex;
    align-items: center;
    width: 100%;
    padding: 10px 12px;

    cursor: pointer;

    .arrow {
      width: 6px;
      height: 12px;
      margin-right: 6px;

      transition: .3s;

      &--top {
        transform: rotate(90deg);
      }

      &--bottom {
        transform: rotate(270deg);
      }
    }
  }

  &__input-text {
    width: 100%;
    margin-right: 12px;
    overflow-x: hidden;

    white-space: nowrap;
    text-overflow: ellipsis;
  }

  &__item {
    display: flex;
    align-items: center;
    padding: 10px 12px;

    border-bottom: 1px solid #F2F2F2;
    cursor: pointer;

    &:first-child {
      border-top: 1px solid #F2F2F2;
    }

    &:last-child {
      border-bottom: none;
    }

    &-checkbox {
      flex-shrink: 0;
      width: 16px;
      height: 16px;
      margin-right: 8px;
    }
  }

  &__item-text {
    width: 100%;
    overflow-x: hidden;

    white-space: nowrap;
    text-overflow: ellipsis;
  }

  &__remove-button {
    display: flex;
    align-items: center;
    padding-bottom: 2px;

    color: var(--color-gray-second);

    border-bottom: 1px solid var(--color-gray-second);

    svg {
      width: 16px;
      height: 16px;
      margin-right: 2px;

      /** Fix empty space on the left */
      margin-left: -3px;
    }
  }
}
</style>

// src/components/customSelects/CustomSelect.tsx
import { ReactElement, useState } from 'react';
import styled from 'styled-components';
import { sansSerifLight } from '../../styles/FontStyles';
import LeftArrowIcon from '../../assets/arrow-left.svg';
import CheckboxIcon from '../../assets/checkbox.svg';
import CheckboxCheckedIcon from '../../assets/checkbox-checked.svg';
import CrossIcon from '../../assets/cross.svg';
import { useTranslation } from 'react-i18next';
import WithClassName from '../../interfaces/WithClassName';

/**
 * Props for custom select elements
 */
interface CustomSelectElementProps {
  /**
   * Is custom select open
   */
  isOpen: boolean;
}

/**
 * Type of options in custom select
 */
export interface Option {
  /**
   * Unique id of option
   */
  id: string;

  /**
   * Displaying value of option
   */
  value: string;
}

interface CustomSelectInputProps extends WithClassName {
  /**
   * onChange event handler
   *
   * @param values - all selected values
   */
  onChange?: (values: Option[]) => void;

  /**
   * Array of selected items
   */
  selected: Option[];

  /**
   * Array of values for displaying
   */
  values: Option[];
}

/**
 * This element needs for displaying select over next elements
 */
export const SelectPlaceholder = styled.div`
  position: relative;

  height: 34px;
  width: 100%;
`;

const SelectWrapper = styled.div<CustomSelectElementProps>`
  position: absolute;

  width: 100%;

  ${ sansSerifLight };
  font-size: 14px;
  color: var(--color-dark-gray);
  user-select: none;

  box-shadow: var(${ props => props.isOpen ? '--shadow-medium' : '--shadow-base' });
  border-radius: 2px;
  overflow: hidden;
  z-index: 1;
`;

const SelectInput = styled.div<CustomSelectElementProps>`
  display: flex;
  align-items: center;

  padding: 5px 12px;

  cursor: pointer;

  &::after {
    height: 24px;
    width: 24px;

    display: block;
    content: '';
    background-image: url("${LeftArrowIcon}");
    background-position: center center;
    background-repeat: no-repeat;

    transform: rotate(${ props => props.isOpen ? '90deg' : '-90deg' });
  }
`;

const SelectInputText = styled.div`
  flex: 1;

  overflow-x: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
`;

const SelectDropdown = styled.ul<CustomSelectElementProps>`
  display: ${ props => props.isOpen ? 'block' : 'none' };
  max-height: 376px;
  overflow-y: auto;

  padding: 0;
  margin: 0;
  list-style-type: none;
  background: var(--color-white);
`;

const ListItem = styled.li`
  display: flex;
  align-items: center;

  border-top: .5px solid var(--color-light-gray);
  padding: 10px 12px;

  cursor: pointer;
`;

/**
 * Props of select item element
 */
interface SelectItemProps {
  /**
   * Is item selected
   */
  selected: boolean;
}

const SelectItem = styled(ListItem)<SelectItemProps>`
  &::before {
    flex-shrink: 0;

    height: 16px;
    width: 16px;

    display: block;
    content: '';
    background-image: url("${ props => props.selected ? CheckboxCheckedIcon : CheckboxIcon }");
    background-size: cover;

    margin-right: 8px;
  }

  &:hover {
    background: var(--color-light-blue);
  }
`;

const SelectItemText = styled.span`
  overflow-x: hidden;
  white-space: nowrap;
  text-overflow: ellipsis;
`;

const SelectResetText = styled.span`
  display: inline-flex;
  align-items: center;

  padding-right: 4px;
  padding-bottom: 4px;
  border-bottom: 1px solid var(--color-gray);
  color: var(--color-gray);

  &::before {
    height: 16px;
    width: 16px;

    content: '';
    background-image: url("${CrossIcon}");
    background-size: cover;
  }
`;

/**
 * Custom select component
 *
 * @param props - props of component
 */
export default function CustomSelect(props: CustomSelectInputProps): ReactElement {
  const { t } = useTranslation();
  const [isOpen, setOpen] = useState(false);

  const findOptionInSelected = (option: Option): boolean => !!props.selected.find(value => value.id === option.id);
  const findIndexOfOptionInSelected = (option: Option): number => props.selected.findIndex(value => value.id === option.id);

  const SelectItems = props.values.map((value, key) => {
    return (
      <SelectItem
        selected={findOptionInSelected(value)}
        onClick={() => {
          if (!props.onChange) {
            return;
          }
          if (findOptionInSelected(value)) {
            const index = findIndexOfOptionInSelected(value);

            props.onChange(props.selected.slice(0, index).concat(props.selected.slice(index + 1)));
          } else {
            props.onChange(props.selected.concat(value));
          }
        }}
        key={key}
      >
        <SelectItemText>{value.value}</SelectItemText>
      </SelectItem>
    );
  });

  return (
    <SelectPlaceholder className={props.className}>
      <SelectWrapper isOpen={isOpen}>
        <SelectInput onClick={() => setOpen(!isOpen)} isOpen={isOpen}>
          <SelectInputText>{
            props.selected.length ? props.selected.map(item => item.value).join(', ') : t('customSelect.placeholder')
          }</SelectInputText>
        </SelectInput>
        <SelectDropdown isOpen={isOpen}>
          {SelectItems}
          <ListItem onClick={() => props.onChange && props.onChange([])}>
            <SelectResetText>{t('customSelect.reset')}</SelectResetText>
          </ListItem>
        </SelectDropdown>
      </SelectWrapper>
    </SelectPlaceholder>
  );
}
