// src/components/SearchLine.vue
<template>
  <div class="search-line">
    <div class="search-line__menu-button">
      <svg
        v-svg
        symbol="menu"
      />
    </div>
    <input
      :id="$id('input')"
      :value="value"
      class="search-line__input"
      type="text"
      :placeholder="$t('inputPlaceholder')"
      @input="$emit('input', $event.target.value)"
    >
    <div class="search-line__search-button">
      <svg
        v-svg
        symbol="search"
      />
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop, Vue } from 'vue-property-decorator';

@Component
/**
 * Search line for searching persons, location, etc
 * Used in Aside bar of the Map view
 */
export default class SearchLine extends Vue {
  @Prop({
    type: String,
    default: ''
  })
  /**
   * Value of the search line for binding
   */
  private value!: string;
}
</script>

<i18n>
{
  "en": {
    "inputPlaceholder": "Enter query..."
  },
  "ru": {
    "inputPlaceholder": "Введите запрос..."
  }
}
</i18n>

<style>
@import "../styles/custom-properties.css";
@import "../styles/variables.css";

.search-line {
  @apply(--box-shadow-main);
  display: flex;
  align-items: center;
  margin-bottom: 12px;
  padding: 12px;

  background: var(--color-white);
  border-radius: 2px;

  &__menu-button {
    width: 24px;
    height: 24px;
    margin-right: 12px;

    cursor: pointer;

    svg {
      width: 100%;
      height: 100%;
    }
  }

  &__input {
    @apply(--font-sans-serif-main);
    flex: 1;
    width: 100%;
    margin-right: 12px;
    padding: 3px 2px;

    color: var(--color-gray-main);

    font-size: 14px;

    background: transparent;
    border: none;
    outline: none;

    &::placeholder {
      @apply(--font-sans-serif-light);
      color: var(--color-gray-second);
    }
  }

  &__search-button {
    width: 24px;
    height: 24px;

    cursor: pointer;

    svg {
      width: 100%;
      height: 100%;
    }
  }
}
</style>

// src/components/SearchLine.tsx
import { ReactElement } from 'react';
import styled from 'styled-components';
import { sansSerifLight, sansSerifRegular } from '../styles/FontStyles';
import BurgerMenuIcon from '../assets/burger-menu.svg';
import SearchIcon from '../assets/search.svg';
import { useTranslation } from 'react-i18next';

const SearchLineWrapper = styled.div`
  display: flex;
  align-items: center;

  background: var(--color-white);
  border-radius: 2px;
  box-shadow: var(--shadow-base);
  padding: 12px;
`;

const SearchLineInput = styled.input`
  width: 100%;

  background: transparent;
  outline: none;
  border: none;
  padding: 3px 2px;
  margin: 0 12px;

  ${ sansSerifRegular };
  font-size: 14px;
  color: var(--color-dark-gray);

  &::placeholder {
    ${ sansSerifLight };
    color: var(--color-light-gray);
  }
`;

const SearchLineButton = styled.button`
  width: 24px;
  height: 24px;

  border: none;
  outline: none;
  background: transparent;

  cursor: pointer;
`;

const SearchLineMenuButton = styled(SearchLineButton)`
  background-image: url("${BurgerMenuIcon}");
  background-size: cover;
`;

const SearchLineSearchButton = styled(SearchLineButton)`
  background-image: url("${SearchIcon}");
  background-size: cover;
`;

/**
 * Search line with menu button
 */
function SearchLine(): ReactElement {
  const { t } = useTranslation();

  return (
    <SearchLineWrapper>
      <SearchLineMenuButton/>
      <SearchLineInput placeholder={t('search.inputPlaceholder')}/>
      <SearchLineSearchButton/>
    </SearchLineWrapper>
  );
}

export default SearchLine;
